s = tf('s'); 
Ga = 1/(s^2+s);
Gb = 1/(s^2+2*s); 
Gc = 1/(s^2+5*s);
subplot(2,2,1);
impulse(Ga,Gb,Gc);
legend('p=1','p=2','p=5');
subplot(2,2,2);
step(Ga,Gb,Gc); 
legend('p=1','p=2','p=5');
t = (0:800)/100;
u = 0*t;
u(t>0 & t<=4)  = 1;
u(t>4 & t<=8) = 2;
subplot(2,2,3);
y1 = lsim(Ga,u,t);
y2 = step(Ga,t);
y3 = y1 + y2;
S1 = stepinfo(y3,t);
disp(S1); 
y4 = lsim(Gb,u,t);
y5 = step(Gb,t);
y6 = y4 + y5;
S2 = stepinfo(y6,t);
disp(S2);
y7 = lsim(Gc,u,t);
y8 = step(Gc,t);
y9 = y7 + y8;
S3 = stepinfo(y9,t);
disp(S3);
plot(t,y3);
hold on;
plot(t,y6);
hold on;
plot(t,y9);
hold off;
title('Step response with disturbance input');
